version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./config:/app/config
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ROUTES_FILE=/app/config/routes.yaml
      - MOCK_MODE=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=api-gateway
      - ADMIN_ENABLED=true
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme
      - RATE_LIMIT_STORAGE=memory
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
