apps:
  - id: payment-paypal
    name: Payment PayPal
    routes:
      - id: payment
        path: /api/payments
        method: POST
        environments:
          integration:
            backend_url: http://localhost:8080/api/payments
            mock: false
            mock_response:
              transactionId: '@transform:transactionId'
              status: '@transform:status'
              amount: '@transform:amount'
              currency: '@transform:currency'
              timestamp: '@transform:timestamp'
          staging:
            backend_url: http://localhost:8080/api/payments
            mock: false
          production:
            backend_url: http://localhost:8080/api/payments
            mock: false
        rate_limit:
          points: 5
          duration: 60
        input:
          validate_schema:
            type: object
            required:
              - amount
              - currency
              - cardDetails
            properties:
              amount:
                type: number
                minimum: 0
              currency:
                type: string
                enum:
                  - EUR
                  - USD
              cardDetails:
                type: object
                required:
                  - number
                  - expiry
                properties:
                  number:
                    type: string
                    pattern: ^[0-9]{16}$
                  expiry:
                    type: string
                    pattern: ^(0[1-9]|1[0-2])/([0-9]{2})$
        input_transform: |
          {
            "amount": amount,
            "currency": currency,
            "card": {
              "number": cardDetails.number,
              "expiry": cardDetails.expiry
            },
            "timestamp": $now()
          }
        timeout: 2s
        output_transform: |
          {
            "transactionId": transactionId,
            "status": status,
            "amount": amount,
            "currency": currency,
            "timestamp": timestamp ? timestamp : $now()
          } 
    environments:
      integration:
        mock: false
